[build]
  publish = "."

[[redirects]]
  from = "/paiement"
  to = "/paiement.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://boutiquemenes.netlify.app/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
